### ISSUE TITLE
Add a way to get group rank via username

### ISSUE THREAD

**Issue by snowstacked** [dovedalewiki/mediawiki-extensions-RobloxAPI#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to suggest a way to get a group rank via username since it's more convenient.

**Describe alternatives you've considered**
Getting group rank via user ID, but can be sometimes inconvenient.

**Comment by SomeMWDev** [comment]
Implemented in #6 with the new `rblxUserId` parser function.

Example:

```
{{#rblxGroupRank: 32670248 | {{#rblxUserId: abaddriverlol}}}}
```
